version: '3.8'

services:
  ts-node-docker:
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    expose: 
      - '3124'
    ports: 
      - '3124:3124'
    command: npm run dev
