# DOCKER
COMPOSE := docker-compose -f ./docker-compose
docker-compose-up:
	$(COMPOSE) up -d

install: 
	echo Install npm package ...
	npm install
test:
	echo Running test ...

dev: 
	echo Running in develop environment ...
	npm run dev
build:
	echo Building ...
	npm run build